spring.application.name=taco
spring.datasource.generate-unique-name=false
spring.datasource.name=tacocloud
spring.cassandra.keyspace-name=taco_cloud
spring.cassandra.schema-action=recreate
spring.cassandra.local-datacenter=datacenter1
spring.mongodb.host=mongodb.tacocloud.com
spring.mongodb.port=27017
spring.mongodb.username=tacocloud
spring.mongodb.password=s3cr3tp455w0rd
spring.mongodb.database=tacoclouddb
